// Contenu bilingue Scalify Labs — porté depuis le site live (version « Clair »)
//   = espace insécable pour garder les groupes de mots ensemble.

export const CONTENT = {
  fr: {
    nav: {
      links: [
        ['services', 'Services'],
        ['methode', 'Méthode'],
        ['preuve', 'Résultats'],
        ['clients', 'Clients'],
        ['secteurs', 'Pour qui'],
      ],
      cta: 'Audit gratuit',
    },
    hero: {
      title: ['Votre publicité,', 'enfin', 'rentable.'],
      rotating: ['tracking serveur', 'arbitrages quotidiens', 'reporting transparent'],
      sub_pre: 'Nous pilotons vos campagnes Meta, Google Ads et TikTok comme un véritable actif — ',
      sub_post: '. Vous savez exactement où va chaque euro — et ',
      sub_accent: "ce qu'il rapporte.",
      cta_primary: 'Demander un audit',
      cta_secondary: 'Voir la méthode',
      availability: 'Reporting transparent · Zéro zone d’ombre',
      scroll: 'Défiler',
    },
    intro: {
      label: 'Présentation',
      bigWords: ['MÉDIA', 'PERFORMANCE', 'DATA', 'ACQUISITION'],
      body: [
        "Agence média indépendante. Nous pilotons l'acquisition payante des marques qui refusent de deviner.",
        'Meta, Google Ads, TikTok — opérés à la main, tracking serveur, créa guidée par la donnée.',
        'Chaque euro investi, tracé. Chaque décision, justifiée.',
      ],
    },
    proof: {
      kicker: 'Ce que nous opérons',
      items: [
        { big: '> 100k€', label: 'Budget média piloté en 2025' },
        { big: '×4,3', label: 'Retour sur dépense pub médian après 90 jours' },
        { big: '−38%', label: "Coût d'acquisition moyen sur les comptes repris" },
      ],
    },
    clients: {
      kicker: 'Ils nous font confiance',
      title: ['Un aperçu', 'de nos clients.'],
      sub: 'Extraits de campagnes réelles.',
      items: [
        { name: 'Biba Brunch', sector: 'Restaurant', metric: '+180% réservations', src: '/reels/biba-brunch.mp4' },
        { name: 'Body Hit', sector: 'Fitness', metric: '×5,2 ROAS', src: '/reels/body-hit.mp4' },
        { name: 'La Clinique Laser', sector: 'Esthétique', metric: '−42% coût/RDV', src: '/reels/clinique-laser.mp4' },
        { name: 'MEB', sector: 'Franchise · Habitat', metric: '+200 prospects générés', src: '/reels/meb.mp4' },
        { name: 'Mamie Bigoude', sector: 'Restaurant', metric: '+45% de couverts', src: '/reels/mamie-bigoude.mp4' },
        { name: 'Piastrella', sector: 'Carrelage · Déco', metric: '×4,1 ROAS', src: '/reels/piastrella.mp4' },
        { name: 'Yujo', sector: 'Restaurant', metric: '1,5 M€ de CA', src: '/reels/yujo.mp4' },
        { name: 'Flash Repair', sector: 'Réparation', metric: '+130 candidatures', src: '/reels/flash-repair.mp4' },
        { name: 'Impact', sector: 'F&B · Recrutement', metric: '+80 candidatures', src: '/reels/impact.mp4' },
        { name: 'Le Roi du Matelas', sector: 'Literie', metric: '−38% CPA', src: '/reels/roi-matelas.mp4' },
        { name: 'Monkey', sector: 'Lifestyle', metric: '×3,4 ROAS', src: '/reels/monkey.mp4' },
        { name: 'Olla Poke', sector: 'Restauration', metric: '+2,1k commandes', src: '/reels/olla-poke.mp4' },
        { name: 'ôCargo', sector: 'Franchise · Mobilité', metric: '+140 candidats franchise', src: '/reels/ocargo.mp4' },
        { name: "Moulin d'Élise", sector: 'Boulangerie', metric: '+60% de trafic', src: '/reels/moulin-elise.mp4' },
        { name: 'The Crying Tiger', sector: 'Restaurant', metric: '×3,9 ROAS', src: '/reels/crying-tiger.mp4' },
        { name: 'Mother & Daughter', sector: 'Mode', metric: '−35% CPA', src: '/reels/mother-daughter.mp4' },
      ],
    },
    work: {
      kicker: 'Showreel',
      title: ['Là où se joue', "l'attention."],
      sub: 'Vos clients scrollent, cherchent, regardent, se déplacent. On opère chaque surface où se capte leur attention — du feed au point de vente.',
      items: [
        { label: 'Le feed', tag: 'Meta · l’attention se capte ici', code: 'SCL-0001/07', src: '/videos/feed.mp4', portrait: true },
        { label: 'Le direct', tag: 'Live & UGC · une audience qui amplifie', code: 'SCL-0002/07', src: '/videos/direct.mp4' },
        { label: 'La recherche', tag: 'Google · l’intention au bon moment', code: 'SCL-0003/07', src: '/videos/search.mp4' },
        { label: 'Le local', tag: 'Maps · jusqu’à votre point de vente', code: 'SCL-0004/07', src: '/videos/local.mp4' },
        { label: "L'e-commerce", tag: 'Conversion · du panier à l’achat', code: 'SCL-0005/07', src: '/videos/ecom.mp4' },
        { label: 'La data', tag: 'Reporting · chaque euro mesuré', code: 'SCL-0006/07', src: '/videos/data.mp4' },
        { label: 'Le tracking', tag: 'Serveur · le moteur sous le capot', code: 'SCL-0007/07', src: '/videos/tracking.mp4' },
      ],
    },
    services: {
      kicker: 'Ce que nous faisons',
      title: ['Trois leviers.', 'Une équipe.'],
      sub_pre: 'Pas de silos, pas de sous-traitance. La même équipe pilote votre acquisition — ',
      sub_accent: 'de la donnée à la création.',
      pillars: [
        {
          k: '01', name: 'Acquisition',
          desc: 'Campagnes Instagram, Facebook, Google Ads et TikTok Ads pilotées de A à Z. Structure, ciblage, enchères — contrôlés à la main, chaque euro justifié.',
          platforms: ['instagram', 'facebook', 'google', 'tiktok'],
        },
        {
          k: '02', name: 'Data & tracking',
          desc: 'Tracking serveur refondu proprement, pour que chaque décision repose sur des chiffres réels — pas sur des suppositions.',
          points: ['Tracking serveur', 'Attribution propre', 'Une seule source de vérité'],
        },
        {
          k: '03', name: 'Stratégie & reporting',
          desc: 'Un plan annuel, une exécution hebdomadaire, et un dashboard en direct. Vous voyez toujours ce que nous voyons.',
          points: ['Plan média annuel', 'Revue hebdomadaire', 'Reporting transparent'],
        },
      ],
      band: {
        kicker: 'Sur-mesure · sur devis',
        title_pre: 'Des besoins complémentaires à votre ',
        title_accent: 'présence digitale ?',
        items: [
          { i: 'site', n: 'Site web' },
          { i: 'app', n: 'Application' },
          { i: 'crm', n: 'Dashboard & CRM' },
        ],
        cta: 'Demander un devis',
      },
    },
    method: {
      kicker: 'Comment ça marche',
      title: ['Quatre étapes.', 'Zéro improvisation.'],
      steps: [
        { k: '01', name: 'Audit', d: 'Semaine 1', desc: "Lecture complète de vos comptes, du suivi et du parcours d'achat. Livré à l'écrit, avec trois leviers immédiats." },
        { k: '02', name: 'Installation', d: 'Semaines 2–3', desc: 'Suivi côté serveur, structure de compte propre, nouveau taggage. Des fondations solides avant tout le reste.' },
        { k: '03', name: 'Scale', d: 'Mois 2+', desc: 'Itération hebdomadaire sur audiences, créations et enchères. Montée en puissance progressive, jamais brutale.' },
        { k: '04', name: 'Reporting', d: 'En continu', desc: 'Tableau de bord en direct, revue mensuelle. Vous avez toujours le même niveau d’information que nous.' },
      ],
    },
    sectors: {
      kicker: 'Pour qui',
      title: ['Vos clients existent.', 'On va les chercher.'],
      sub_pre: 'Que vous soyez seul ou à la tête d’un réseau, notre métier reste le même : ',
      sub_accent: 'vous amener des clients.',
      niches: ['votre métier', 'votre cabinet', 'votre commerce', 'votre secteur'],
      notListed: 'Pas dans la liste ?',
      notListedPre: 'On couvre sûrement ',
      notListedPost: ' aussi.',
      ask: 'Demandez-nous',
      items: [
        { icon: 'retail', name: 'Commerces & boutiques', desc: 'Magasins, showrooms, points de vente' },
        { icon: 'resto', name: 'Restauration', desc: 'Restaurants, boulangeries, cafés' },
        { icon: 'sante', name: 'Santé & praticiens', desc: 'Cabinets, dentistes, kinés, bien-être' },
        { icon: 'conseil', name: 'Professions libérales', desc: 'Avocats, notaires, experts-comptables, conseil' },
        { icon: 'beaute', name: 'Beauté & bien-être', desc: 'Salons, spas, coachs' },
        { icon: 'immo', name: 'Immobilier', desc: 'Agences, promoteurs, courtiers' },
        { icon: 'b2b', name: 'Services aux entreprises', desc: 'B2B, agences, logiciels, cabinets' },
        { icon: 'ecom', name: 'E-commerce & marques', desc: 'Vente directe, boutiques en ligne' },
        { icon: 'sport', name: 'Sport & fitness', desc: 'Clubs, studios, réseaux' },
        { icon: 'formation', name: 'Éducation & formation', desc: 'Écoles, coachs, formations en ligne' },
      ],
    },
    franchise: {
      tag: 'Réseaux de franchise',
      title: 'Vous développez un réseau ou recrutez des franchisés ?',
      desc: 'Nous pilotons deux moteurs en parallèle — avec un reporting consolidé pour le siège.',
      cta: 'Parler de mon réseau',
      engines: [
        { label: 'Moteur 01', name: 'Remplir vos points de vente', desc: 'Acquisition locale géociblée, par point de vente.', metric: 'En boutique & en ligne' },
        { label: 'Moteur 02', name: 'Recruter des franchisés', desc: 'Un tunnel dédié pour attirer, qualifier et convertir les candidats.', metric: 'Candidats qualifiés / mois' },
      ],
    },
    contact: {
      kicker: 'Prendre contact',
      title: 'Parlons de vos comptes.',
      sub: 'Un audit gratuit de 45 minutes. Nous regardons vos comptes en direct, identifions trois leviers immédiats, et vous remettons un document écrit. Aucun engagement.',
      bullets: ['Audit gratuit de 45 minutes', '3 leviers immédiats, à l’écrit', 'Réponse sous 24 h', 'Sans engagement'],
      fields: { firstname: 'Prénom', name: 'Nom', company: 'Société', email: 'Email', phone: 'Téléphone', message: 'Contexte' },
      submit: 'Envoyer la demande',
      sentTitle: 'Merci',
      sentBody: 'Nous revenons vers vous sous 48 heures ouvrées.',
    },
    footer: {
      tagline: 'Agence média indépendante.',
      navTitle: 'Navigation',
      copy: '© 2026 Scalify Labs · Tous droits réservés',
    },
    end: {
      kicker: 'Prêt à parler ?',
      go: 'GO',
      big: 'ON Y VA',
      line: 'Un audit gratuit de 45 minutes. Sans engagement.',
      email: 'contact@scalifylabs.com',
    },
    mascot: {
      lines: {
        top: 'On va chercher vos clients 🦊',
        preuve: 'Ces chiffres ? Vérifiables.',
        clients: 'Vos créas, dans ce mur. 🎬',
        services: 'Trois leviers, une équipe.',
        work: 'Ça défile → scrolle',
        methode: 'Méthode > impro, toujours.',
        secteurs: 'Votre secteur ? On le couvre.',
        contact: 'On se parle ? 👋',
      },
      nudge: 'Un audit gratuit ?',
      cookie: {
        q: 'Un petit cookie ? 🍪',
        txt: 'On en grignote quelques-uns pour mesurer l’audience. Tu es d’accord ?',
        accept: 'Accepter',
        refuse: 'Refuser',
        menu: 'Cookies 🍪',
        done: 'Miam, merci ! 🍪',
      },
    },
  },

  en: {
    nav: {
      links: [
        ['services', 'Services'],
        ['methode', 'Method'],
        ['preuve', 'Results'],
        ['clients', 'Clients'],
        ['secteurs', 'Who for'],
      ],
      cta: 'Free audit',
    },
    hero: {
      title: ['Your ads,', 'finally', 'profitable.'],
      rotating: ['server-side tracking', 'daily arbitrage', 'transparent reporting'],
      sub_pre: 'We run your Meta, Google Ads and TikTok campaigns like a real asset — ',
      sub_post: '. You know exactly where every euro goes — and ',
      sub_accent: 'what it returns.',
      cta_primary: 'Request an audit',
      cta_secondary: 'See the method',
      availability: 'Transparent reporting · Zero blind spots',
      scroll: 'Scroll',
    },
    intro: {
      label: 'About',
      bigWords: ['MEDIA', 'PERFORMANCE', 'DATA', 'ACQUISITION'],
      body: [
        'Independent media agency. We run paid acquisition for brands that refuse to guess.',
        'Meta, Google Ads, TikTok — operated by hand, server-side tracking, data-led creative.',
        'Every euro spent, tracked. Every call, justified.',
      ],
    },
    proof: {
      kicker: 'What we operate',
      items: [
        { big: '> €100k', label: 'Media spend managed in 2025' },
        { big: '×4.3', label: 'Median return on ad spend after 90 days' },
        { big: '−38%', label: 'Avg. acquisition cost on accounts taken over' },
      ],
    },
    clients: {
      kicker: 'Trusted by',
      title: ['A glimpse', 'of our clients.'],
      sub: 'Cuts from real campaigns.',
      items: [
        { name: 'Biba Brunch', sector: 'Restaurant', metric: '+180% bookings', src: '/reels/biba-brunch.mp4' },
        { name: 'Body Hit', sector: 'Fitness', metric: '×5.2 ROAS', src: '/reels/body-hit.mp4' },
        { name: 'La Clinique Laser', sector: 'Aesthetics', metric: '−42% cost/appt.', src: '/reels/clinique-laser.mp4' },
        { name: 'MEB', sector: 'Franchise · Home', metric: '+200 leads generated', src: '/reels/meb.mp4' },
        { name: 'Mamie Bigoude', sector: 'Restaurant', metric: '+45% covers', src: '/reels/mamie-bigoude.mp4' },
        { name: 'Piastrella', sector: 'Tiling · Decor', metric: '×4.1 ROAS', src: '/reels/piastrella.mp4' },
        { name: 'Yujo', sector: 'Restaurant', metric: '€1.5M revenue', src: '/reels/yujo.mp4' },
        { name: 'Flash Repair', sector: 'Repair', metric: '+130 applications', src: '/reels/flash-repair.mp4' },
        { name: 'Impact', sector: 'F&B · Recruitment', metric: '+80 applications', src: '/reels/impact.mp4' },
        { name: 'Le Roi du Matelas', sector: 'Bedding', metric: '−38% CPA', src: '/reels/roi-matelas.mp4' },
        { name: 'Monkey', sector: 'Lifestyle', metric: '×3.4 ROAS', src: '/reels/monkey.mp4' },
        { name: 'Olla Poke', sector: 'Food', metric: '+2.1k orders', src: '/reels/olla-poke.mp4' },
        { name: 'ôCargo', sector: 'Franchise · Mobility', metric: '+140 franchise leads', src: '/reels/ocargo.mp4' },
        { name: "Moulin d'Élise", sector: 'Bakery', metric: '+60% foot traffic', src: '/reels/moulin-elise.mp4' },
        { name: 'The Crying Tiger', sector: 'Restaurant', metric: '×3.9 ROAS', src: '/reels/crying-tiger.mp4' },
        { name: 'Mother & Daughter', sector: 'Fashion', metric: '−35% CPA', src: '/reels/mother-daughter.mp4' },
      ],
    },
    work: {
      kicker: 'Showreel',
      title: ['Where attention', 'happens.'],
      sub: 'Your customers scroll, search, watch, move. We operate every surface where their attention lives — from the feed to the storefront.',
      items: [
        { label: 'The feed', tag: 'Meta · where attention is captured', code: 'SCL-0001/07', src: '/videos/feed.mp4', portrait: true },
        { label: 'The live', tag: 'Live & UGC · an audience that amplifies', code: 'SCL-0002/07', src: '/videos/direct.mp4' },
        { label: 'The search', tag: 'Google · intent at the right moment', code: 'SCL-0003/07', src: '/videos/search.mp4' },
        { label: 'The map', tag: 'Maps · all the way to your storefront', code: 'SCL-0004/07', src: '/videos/local.mp4' },
        { label: 'E-commerce', tag: 'Conversion · from cart to purchase', code: 'SCL-0005/07', src: '/videos/ecom.mp4' },
        { label: 'The data', tag: 'Reporting · every euro measured', code: 'SCL-0006/07', src: '/videos/data.mp4' },
        { label: 'Tracking', tag: 'Server-side · the engine under the hood', code: 'SCL-0007/07', src: '/videos/tracking.mp4' },
      ],
    },
    services: {
      kicker: 'What we do',
      title: ['Three levers.', 'One team.'],
      sub_pre: 'No silos, no outsourcing. The same team owns your acquisition — ',
      sub_accent: 'from the data to the creative.',
      pillars: [
        {
          k: '01', name: 'Acquisition',
          desc: 'Instagram, Facebook, Google Ads and TikTok Ads run end to end. Structure, targeting, bidding — controlled by hand, every euro accounted for.',
          platforms: ['instagram', 'facebook', 'google', 'tiktok'],
        },
        {
          k: '02', name: 'Data & tracking',
          desc: 'Server-side tracking rebuilt from scratch, so every decision rests on real numbers — not guesses.',
          points: ['Server-side tracking', 'Clean attribution', 'Single source of truth'],
        },
        {
          k: '03', name: 'Strategy & reporting',
          desc: 'An annual plan, weekly execution, and a live dashboard. You always see what we see.',
          points: ['Annual media plan', 'Weekly review', 'Transparent reporting'],
        },
      ],
      band: {
        kicker: 'Custom · on quote',
        title_pre: 'Complementary needs to your ',
        title_accent: 'digital presence?',
        items: [
          { i: 'site', n: 'Website' },
          { i: 'app', n: 'Application' },
          { i: 'crm', n: 'Dashboard & CRM' },
        ],
        cta: 'Request a quote',
      },
    },
    method: {
      kicker: 'How it works',
      title: ['Four steps.', 'No improvisation.'],
      steps: [
        { k: '01', name: 'Audit', d: 'Week 1', desc: 'A full read of your accounts, tracking and buying journey. Delivered in writing, with three immediate levers.' },
        { k: '02', name: 'Setup', d: 'Weeks 2–3', desc: 'Server-side tracking, clean account structure, new tagging. Solid foundations before anything else.' },
        { k: '03', name: 'Scale', d: 'Month 2+', desc: 'Weekly iteration on audiences, creative and bids. Gradual, controlled ramp-up — never brutal.' },
        { k: '04', name: 'Report', d: 'Ongoing', desc: 'Live dashboard, monthly review. You always have the same level of information as us.' },
      ],
    },
    sectors: {
      kicker: 'Who we work with',
      title: ['Your customers are out there.', 'We go and get them.'],
      sub_pre: 'Whether you run a single location or a national network, our job stays the same: ',
      sub_accent: 'bringing you customers.',
      niches: ['your niche', 'your practice', 'your shop', 'your field'],
      notListed: 'Not listed?',
      notListedPre: 'We probably cover ',
      notListedPost: ' too.',
      ask: 'Ask us',
      items: [
        { icon: 'retail', name: 'Retail & shops', desc: 'Stores, showrooms, points of sale' },
        { icon: 'resto', name: 'Food & hospitality', desc: 'Restaurants, bakeries, cafés' },
        { icon: 'sante', name: 'Health & practitioners', desc: 'Clinics, dentists, physios, wellbeing' },
        { icon: 'conseil', name: 'Liberal professions', desc: 'Lawyers, notaries, accountants, consultants' },
        { icon: 'beaute', name: 'Beauty & wellbeing', desc: 'Salons, spas, coaches' },
        { icon: 'immo', name: 'Real estate', desc: 'Agencies, developers, brokers' },
        { icon: 'b2b', name: 'Business services', desc: 'B2B, agencies, SaaS, firms' },
        { icon: 'ecom', name: 'E-commerce & brands', desc: 'Direct-to-consumer, online shops' },
        { icon: 'sport', name: 'Sport & fitness', desc: 'Clubs, studios, franchises' },
        { icon: 'formation', name: 'Education & training', desc: 'Schools, coaches, online courses' },
      ],
    },
    franchise: {
      tag: 'Franchise networks',
      title: 'Scaling a network or recruiting franchisees?',
      desc: 'We run two engines in parallel — with consolidated reporting for HQ.',
      cta: 'Discuss my network',
      engines: [
        { label: 'Engine 01', name: 'Fill your locations', desc: 'Geo-targeted local acquisition, per point of sale.', metric: 'In-store & online' },
        { label: 'Engine 02', name: 'Recruit franchisees', desc: 'A dedicated funnel to attract, qualify and convert candidates.', metric: 'Qualified leads / month' },
      ],
    },
    contact: {
      kicker: 'Get in touch',
      title: "Let's talk about your accounts.",
      sub: 'A free 45-minute audit. We look at your accounts live, identify three immediate levers, and hand you a written document. No commitment.',
      bullets: ['Free 45-minute audit', '3 immediate levers, in writing', 'Reply within 24 h', 'No commitment, ever'],
      fields: { firstname: 'First name', name: 'Last name', company: 'Company', email: 'Email', phone: 'Phone', message: 'Context' },
      submit: 'Send request',
      sentTitle: 'Thanks',
      sentBody: "We'll get back to you within 48 business hours.",
    },
    footer: {
      tagline: 'Independent paid media agency.',
      navTitle: 'Navigation',
      copy: '© 2026 Scalify Labs · All rights reserved',
    },
    end: {
      kicker: 'Ready to talk?',
      go: 'GO',
      big: "LET'S GO",
      line: 'A free 45-minute audit. No commitment.',
      email: 'contact@scalifylabs.com',
    },
    mascot: {
      lines: {
        top: "Let's go hunt your customers 🦊",
        preuve: 'These numbers? Verifiable.',
        clients: 'Your creatives, on this wall. 🎬',
        services: 'Three levers, one team.',
        work: 'Scroll → it moves',
        methode: 'Method > improv, always.',
        secteurs: 'Your field? We cover it.',
        contact: "Let's talk? 👋",
      },
      nudge: 'Want a free audit?',
      cookie: {
        q: 'A cookie? 🍪',
        txt: 'We nibble a few to measure traffic. Are you in?',
        accept: 'Accept',
        refuse: 'Decline',
        menu: 'Cookies 🍪',
        done: 'Yum, thanks! 🍪',
      },
    },
  },
}

export const SECTION_IDS = ['top', 'preuve', 'clients', 'services', 'methode', 'secteurs', 'contact']
